spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petshop?serverTimezone=GMT&useSSL=false
    username: root
    password: '000000'
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 10
    maxWait: 3000